name: osta
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  equatable: ^2.0.5
  cloud_firestore: ^4.11.0
  shared_preferences: ^2.2.2
  dartz: ^0.10.1
  curved_navigation_bar: ^1.0.3
  dot_navigation_bar: ^1.0.2
  dot_bottom_nav: ^0.0.2
  animated_bottom_navigation_bar:
  carousel_slider: ^4.2.1
  dotted_border: ^2.1.0
  internet_connection_checker: ^1.0.0+1
  url_launcher: ^6.2.2
  line_icons: ^2.0.3
  iconsax_flutter: ^1.0.0
  calendar_date_picker2: ^0.5.3
  another_stepper: ^1.2.2
  flutter_screenutil: ^5.9.0
  pixel_perfect: ^1.1.3
  flutter_svg: ^2.0.9
  scrollable_positioned_list: ^0.3.8
  device_info_plus: ^9.1.1
  image_picker: ^1.0.7
  hydrated_bloc: ^9.1.4
  cached_network_image: ^3.3.1
  file_picker: ^6.1.1
  flutter_colorpicker: ^1.0.3
  bloc_concurrency: ^0.2.4
  infinite_scroll_pagination: ^4.0.0
  share_plus: ^7.2.2
  flutter_native_splash:
#  pull_to_refresh: ^2.0.0

#  flutter_rounded_date_picker: ^3.0.4
#  flutter_svg: ^2.0.9
#  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1


flutter_native_splash:
  color: "#ffffff"
  image: assets/images/osta_logo.png
  fullscreen: true
#  branding: assets/branding-development.png
#  color_dark: "#121212"
#  image_dark: assets/logo-development.png
#  branding_dark: assets/branding-development.png

  android_12:
    image: assets/images/osta_logo.png
#    icon_background_color: "#ffffff"
#    image_dark: assets/logo-development.png
#    icon_background_color_dark: "#121212"

#  web: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/osta_logo.png"


  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/waiting_images/
    - assets/images/main_services_logos/
    - assets/images/joinus_assets/
    - assets/lang/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
        - asset: assets/fonts/SpaceGrotesk-Light.ttf
        - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf
          weight: 700
    - family: OstaCustomIcons
      fonts:
        - asset: assets/fonts/OstaCustomIcons.ttf

