/// Flutter icons OstaCustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OstaCustomIcons
///      fonts:
///       - asset: fonts/OstaCustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class OstaCustomIcons {
  OstaCustomIcons._();

  static const _kFontFam = 'OstaCustomIcons';
  static const String? _kFontPkg = null;

  static const IconData home = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData join = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData requests = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting2 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData worker = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teamwork_1 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warehouse = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direct_inbox = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_circle = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note_2 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
