import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:osta/core/localization/app_localizations.dart';
import 'package:osta/core/utils/app_text_styles.dart';
import 'package:osta/presentation/components/custom_app_bar.dart';
import 'package:osta/presentation/components/join_application_components/label_text.dart';

class TermsAndConditionScreen extends StatelessWidget {
  const TermsAndConditionScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: CustomAppBar(title:
      'setting.about'.tr(context)),
      body: SingleChildScrollView(
        padding: EdgeInsets.symmetric(horizontal: 32.w,vertical: 12.h),
        child: Text(
            style: AppTextStyles.title2TextStyle,
            textAlign: TextAlign.start,
            softWrap: true,

        '''
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque egestas congue quisque egestas diam. Volutpat blandit aliquam etiam erat velit scelerisque. Enim eu turpis egestas pretium aenean pharetra magna. Ac odio tempor orci dapibus. Massa massa ultricies mi quis hendrerit dolor magna eget. Etiam erat velit scelerisque in dictum non consectetur. Egestas dui id ornare arcu odio. Purus semper eget duis at tellus. Ultricies integer quis auctor elit sed vulputate mi.

Nulla pellentesque dignissim enim sit amet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Gravida dictum fusce ut placerat orci. Fames ac turpis egestas integer eget aliquet. Quam pellentesque nec nam aliquam sem et tortor. Proin libero nunc consequat interdum varius sit amet mattis. Sed risus ultricies tristique nulla aliquet enim. Praesent tristique magna sit amet purus. Nam aliquam sem et tortor. Nunc scelerisque viverra mauris in aliquam. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor. Nec dui nunc mattis enim ut tellus elementum sagittis.

Eu facilisis sed odio morbi quis commodo. Nisl suscipit adipiscing bibendum est ultricies integer. Purus sit amet volutpat consequat mauris. Ut tristique et egestas quis ipsum suspendisse ultrices. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Varius quam quisque id diam vel quam elementum pulvinar etiam. Ipsum dolor sit amet consectetur adipiscing. Massa placerat duis ultricies lacus sed turpis. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Ut sem nulla pharetra diam. Ut placerat orci nulla pellentesque dignissim enim sit. Sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Eget nulla facilisi etiam dignissim diam quis.

Nunc aliquet bibendum enim facilisis gravida neque. Pharetra vel turpis nunc eget lorem dolor. At augue eget arcu dictum. Fusce id velit ut tortor pretium viverra. Quis hendrerit dolor magna eget est lorem ipsum. Sit amet facilisis magna etiam tempor. Consequat ac felis donec et odio. Etiam tempor orci eu lobortis. Consequat interdum varius sit amet mattis vulputate enim. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Vulputate odio ut enim blandit volutpat maecenas. Sagittis purus sit amet volutpat consequat mauris nunc. Tortor aliquam nulla facilisi cras fermentum odio. Ac turpis egestas sed tempus urna et. Tortor consequat id porta nibh venenatis. In pellentesque massa placerat duis ultricies lacus sed. Sollicitudin nibh sit amet commodo nulla facilisi nullam. Porttitor massa id neque aliquam vestibulum morbi. Amet nulla facilisi morbi tempus iaculis urna id volutpat lacus.

At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Commodo sed egestas egestas fringilla phasellus. Dui sapien eget mi proin sed libero. In arcu cursus euismod quis viverra nibh. Placerat vestibulum lectus mauris ultrices eros in cursus. Pharetra magna ac placerat vestibulum. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Enim ut sem viverra aliquet. Aliquet nibh praesent tristique magna sit amet purus gravida. Velit euismod in pellentesque massa. Turpis egestas sed tempus urna et pharetra pharetra. Tellus cras adipiscing enim eu. Pellentesque sit amet porttitor eget dolor.

Posuere urna nec tincidunt praesent semper. Nunc lobortis mattis aliquam faucibus purus in massa. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis commodo odio aenean sed adipiscing. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Lacus viverra vitae congue eu consequat ac felis donec. Euismod nisi porta lorem mollis aliquam ut porttitor. Turpis cursus in hac habitasse. Vestibulum morbi blandit cursus risus at ultrices mi. Habitant morbi tristique senectus et netus. Adipiscing commodo elit at imperdiet dui accumsan sit amet nulla. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Leo a diam sollicitudin tempor id eu. Egestas fringilla phasellus faucibus scelerisque eleifend donec. Viverra justo nec ultrices dui.

Dictum non consectetur a erat. Parturient montes nascetur ridiculus mus mauris. Praesent semper feugiat nibh sed pulvinar proin gravida. Integer enim neque volutpat ac tincidunt vitae semper quis lectus. Porta lorem mollis aliquam ut porttitor leo a diam sollicitudin. Feugiat in ante metus dictum at tempor commodo ullamcorper. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Et malesuada fames ac turpis egestas maecenas pharetra. Dictum fusce ut placerat orci nulla. Purus sit amet volutpat consequat mauris nunc congue nisi. Donec massa sapien faucibus et molestie. Mauris vitae ultricies leo integer. Purus non enim praesent elementum facilisis leo vel fringilla. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Facilisis mauris sit amet massa vitae tortor. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Vulputate eu scelerisque felis imperdiet proin fermentum leo. Tempor nec feugiat nisl pretium. Ac tincidunt vitae semper quis lectus nulla.

Pulvinar mattis nunc sed blandit libero volutpat sed cras. Tincidunt dui ut ornare lectus sit amet est placerat in. Ac feugiat sed lectus vestibulum mattis. Ac orci phasellus egestas tellus rutrum tellus pellentesque eu. Accumsan lacus vel facilisis volutpat est. Tincidunt praesent semper feugiat nibh sed pulvinar proin. Blandit volutpat maecenas volutpat blandit. Nibh ipsum consequat nisl vel. Enim sit amet venenatis urna cursus eget nunc scelerisque viverra. Volutpat ac tincidunt vitae semper. Ut placerat orci nulla pellentesque dignissim enim sit amet. Arcu vitae elementum curabitur vitae nunc sed. Erat pellentesque adipiscing commodo elit at. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse. Pretium fusce id velit ut tortor. Ornare suspendisse sed nisi lacus sed viverra tellus in hac.

Convallis tellus id interdum velit. Non sodales neque sodales ut etiam sit amet nisl purus. Interdum velit laoreet id donec ultrices tincidunt arcu. Scelerisque eu ultrices vitae auctor eu augue ut. Tincidunt arcu non sodales neque sodales ut etiam sit amet. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus. Porttitor eget dolor morbi non arcu risus quis. Habitant morbi tristique senectus et. Et malesuada fames ac turpis egestas. Nulla facilisi morbi tempus iaculis urna. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt.

Cursus mattis molestie a iaculis. Id consectetur purus ut faucibus pulvinar elementum integer enim. Ut venenatis tellus in metus vulputate eu. Mauris commodo quis imperdiet massa tincidunt. Libero id faucibus nisl tincidunt eget. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Tempus iaculis urna id volutpat. Lectus urna duis convallis convallis tellus. Morbi enim nunc faucibus a pellentesque sit amet porttitor. Neque sodales ut etiam sit amet. Aliquet nibh praesent tristique magna sit amet. Malesuada fames ac turpis egestas integer eget aliquet nibh. Pulvinar pellentesque habitant morbi tristique senectus. Tincidunt augue interdum velit euismod in pellentesque massa placerat duis. Cursus turpis massa tincidunt dui ut ornare lectus sit. Euismod lacinia at quis risus sed. Vitae semper quis lectus nulla at. Ut sem viverra aliquet eget sit amet tellus cras. Pulvinar elementum integer enim neque volutpat ac tincidunt vitae semper.
 
 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque egestas congue quisque egestas diam. Volutpat blandit aliquam etiam erat velit scelerisque. Enim eu turpis egestas pretium aenean pharetra magna. Ac odio tempor orci dapibus. Massa massa ultricies mi quis hendrerit dolor magna eget. Etiam erat velit scelerisque in dictum non consectetur. Egestas dui id ornare arcu odio. Purus semper eget duis at tellus. Ultricies integer quis auctor elit sed vulputate mi.

Nulla pellentesque dignissim enim sit amet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Gravida dictum fusce ut placerat orci. Fames ac turpis egestas integer eget aliquet. Quam pellentesque nec nam aliquam sem et tortor. Proin libero nunc consequat interdum varius sit amet mattis. Sed risus ultricies tristique nulla aliquet enim. Praesent tristique magna sit amet purus. Nam aliquam sem et tortor. Nunc scelerisque viverra mauris in aliquam. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor. Nec dui nunc mattis enim ut tellus elementum sagittis.

Eu facilisis sed odio morbi quis commodo. Nisl suscipit adipiscing bibendum est ultricies integer. Purus sit amet volutpat consequat mauris. Ut tristique et egestas quis ipsum suspendisse ultrices. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Varius quam quisque id diam vel quam elementum pulvinar etiam. Ipsum dolor sit amet consectetur adipiscing. Massa placerat duis ultricies lacus sed turpis. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Ut sem nulla pharetra diam. Ut placerat orci nulla pellentesque dignissim enim sit. Sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Eget nulla facilisi etiam dignissim diam quis.

Nunc aliquet bibendum enim facilisis gravida neque. Pharetra vel turpis nunc eget lorem dolor. At augue eget arcu dictum. Fusce id velit ut tortor pretium viverra. Quis hendrerit dolor magna eget est lorem ipsum. Sit amet facilisis magna etiam tempor. Consequat ac felis donec et odio. Etiam tempor orci eu lobortis. Consequat interdum varius sit amet mattis vulputate enim. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Vulputate odio ut enim blandit volutpat maecenas. Sagittis purus sit amet volutpat consequat mauris nunc. Tortor aliquam nulla facilisi cras fermentum odio. Ac turpis egestas sed tempus urna et. Tortor consequat id porta nibh venenatis. In pellentesque massa placerat duis ultricies lacus sed. Sollicitudin nibh sit amet commodo nulla facilisi nullam. Porttitor massa id neque aliquam vestibulum morbi. Amet nulla facilisi morbi tempus iaculis urna id volutpat lacus.

At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Commodo sed egestas egestas fringilla phasellus. Dui sapien eget mi proin sed libero. In arcu cursus euismod quis viverra nibh. Placerat vestibulum lectus mauris ultrices eros in cursus. Pharetra magna ac placerat vestibulum. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Enim ut sem viverra aliquet. Aliquet nibh praesent tristique magna sit amet purus gravida. Velit euismod in pellentesque massa. Turpis egestas sed tempus urna et pharetra pharetra. Tellus cras adipiscing enim eu. Pellentesque sit amet porttitor eget dolor.

Posuere urna nec tincidunt praesent semper. Nunc lobortis mattis aliquam faucibus purus in massa. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis commodo odio aenean sed adipiscing. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Lacus viverra vitae congue eu consequat ac felis donec. Euismod nisi porta lorem mollis aliquam ut porttitor. Turpis cursus in hac habitasse. Vestibulum morbi blandit cursus risus at ultrices mi. Habitant morbi tristique senectus et netus. Adipiscing commodo elit at imperdiet dui accumsan sit amet nulla. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Leo a diam sollicitudin tempor id eu. Egestas fringilla phasellus faucibus scelerisque eleifend donec. Viverra justo nec ultrices dui.

Dictum non consectetur a erat. Parturient montes nascetur ridiculus mus mauris. Praesent semper feugiat nibh sed pulvinar proin gravida. Integer enim neque volutpat ac tincidunt vitae semper quis lectus. Porta lorem mollis aliquam ut porttitor leo a diam sollicitudin. Feugiat in ante metus dictum at tempor commodo ullamcorper. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Et malesuada fames ac turpis egestas maecenas pharetra. Dictum fusce ut placerat orci nulla. Purus sit amet volutpat consequat mauris nunc congue nisi. Donec massa sapien faucibus et molestie. Mauris vitae ultricies leo integer. Purus non enim praesent elementum facilisis leo vel fringilla. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Facilisis mauris sit amet massa vitae tortor. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Vulputate eu scelerisque felis imperdiet proin fermentum leo. Tempor nec feugiat nisl pretium. Ac tincidunt vitae semper quis lectus nulla.

Pulvinar mattis nunc sed blandit libero volutpat sed cras. Tincidunt dui ut ornare lectus sit amet est placerat in. Ac feugiat sed lectus vestibulum mattis. Ac orci phasellus egestas tellus rutrum tellus pellentesque eu. Accumsan lacus vel facilisis volutpat est. Tincidunt praesent semper feugiat nibh sed pulvinar proin. Blandit volutpat maecenas volutpat blandit. Nibh ipsum consequat nisl vel. Enim sit amet venenatis urna cursus eget nunc scelerisque viverra. Volutpat ac tincidunt vitae semper. Ut placerat orci nulla pellentesque dignissim enim sit amet. Arcu vitae elementum curabitur vitae nunc sed. Erat pellentesque adipiscing commodo elit at. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse. Pretium fusce id velit ut tortor. Ornare suspendisse sed nisi lacus sed viverra tellus in hac.

Convallis tellus id interdum velit. Non sodales neque sodales ut etiam sit amet nisl purus. Interdum velit laoreet id donec ultrices tincidunt arcu. Scelerisque eu ultrices vitae auctor eu augue ut. Tincidunt arcu non sodales neque sodales ut etiam sit amet. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus. Porttitor eget dolor morbi non arcu risus quis. Habitant morbi tristique senectus et. Et malesuada fames ac turpis egestas. Nulla facilisi morbi tempus iaculis urna. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt.

Cursus mattis molestie a iaculis. Id consectetur purus ut faucibus pulvinar elementum integer enim. Ut venenatis tellus in metus vulputate eu. Mauris commodo quis imperdiet massa tincidunt. Libero id faucibus nisl tincidunt eget. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Tempus iaculis urna id volutpat. Lectus urna duis convallis convallis tellus. Morbi enim nunc faucibus a pellentesque sit amet porttitor. Neque sodales ut etiam sit amet. Aliquet nibh praesent tristique magna sit amet. Malesuada fames ac turpis egestas integer eget aliquet nibh. Pulvinar pellentesque habitant morbi tristique senectus. Tincidunt augue interdum velit euismod in pellentesque massa placerat duis. Cursus turpis massa tincidunt dui ut ornare lectus sit. Euismod lacinia at quis risus sed. Vitae semper quis lectus nulla at. Ut sem viverra aliquet eget sit amet tellus cras. Pulvinar elementum integer enim neque volutpat ac tincidunt vitae semper.
        '''
        ),
      ),
    );
  }
}
